baseURL = 'https://zhruyun.github.io/'
locale = 'zh-cn'
title = 'My Blog'
theme = 'PaperMod'

[params]
    defaultTheme = "auto" # 自动切换夜间模式
    showToc = true        # 是否显示文章目录
    TocOpen = true        # 是否默认展开目录